
.. attention::

   ``--v1`` and ``--v2c`` options are available since glpi-agent 1.5

   ``--backend-collect-timeout`` option is available since glpi-agent 1.6

   ``--retries`` option is available since glpi-agent 1.9

   ``--glpi-version`` option is available since glpi-agent 1.16

   ``--features`` option is available since glpi-agent 1.20

   ``--iec-dump`` and ``--iec-file`` options are available since glpi-agent 1.20
