
.. hint::

   Configuration options are also documented on the :doc:`../configuration` page.

.. attention::

   ``--assetname-support`` option is available since glpi-agent 1.5

   ``--full-inventory-postpone`` and ``--full`` options are available since glpi-agent 1.8

   ``--oauth-client-id`` and ``--oauth-client-secret`` options are available since glpi-agent 1.10

   ``--glpi-version`` option is available since glpi-agent 1.12

   ``--required-category``, ``--itemtype`` and `--esx-itemtype`` options are available since glpi-agent 1.13

   ``--proxy`` option supports ``none`` value to not use environment variable since glpi-agent 1.13
