
.. attention::

   ``--proxy`` options is available since glpi-agent 1.5

   ``--oauth-client-id`` and ``--oauth-client-secret`` options are available since glpi-agent 1.10

   ``--ca-cert-file``, ``--ssl-fingerprint`` and ``--ssl-key-file`` options are available since glpi-agent 1.16

   ``--debug --no-ssl-check`` options with ``glpi-injector`` can be used since glpi-agent 1.16 to show server ``--ssl-fingerprint`` possible value.